name: "[production] Build image, push to custom registry, deploy to Caprover"

on:
  push:
    branches:
      - main

env:
  IMAGE_REPO: registry.minsky.cc/minskylab/qronica/core

jobs:
  build-push-registry:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: registry.minsky.cc
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ env.IMAGE_REPO }}:${{ github.sha }}
            ${{ env.IMAGE_REPO }}:stable
            ${{ env.IMAGE_REPO }}:latest
  deploy-caprover:
    runs-on: ubuntu-20.04
    needs: [build-push-registry]
    steps:
      - name: Deploy to Caprover
        uses: floms/action-caprover@v1
        with:
          host: "${{ secrets.CAPROVER_HOST }}"
          password: "${{ secrets.CAPROVER_PASSWORD }}"
          app: "${{ secrets.CAPROVER_APP_PRODUCTION }}"
          image: "${{ env.IMAGE_REPO }}:${{ github.sha }}"